/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.aytomonzon.librosac;

import java.awt.Component;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableRowSorter;

/**
 * Clase que presenta los movimientos diarios de un trabajador
 * @author albertoaraguas
 * @version 1.0
 * 
 */
public class DiarioMovimientoIndividual extends javax.swing.JFrame {
  
    /**
     * Creates new form DiarioMovimientoIndividual
     * @param miModelo2 es un defaultTablamodel ya creado, ya que solo lo pinta en el jframe
     * @param Nombre Nombre del trabajador
     */
    public DiarioMovimientoIndividual(DefaultTableModel  miModelo2 , String Nombre) {
        
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);   //con esto volvemos al jframe principal sin cerrar el programa
        //pintar cargar el jtable con los datos pasados de la consulta
        this.LblTrabajador.setText(Nombre);
        //hacer consulta del diario en la base de datos
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(miModelo2);
        this.jTable1.setModel(miModelo2);
        this.jTable1.setRowSorter(sorter);
        // Ajustar el ancho de las columnas
        TableColumnModel columnModel = jTable1.getColumnModel();
        for (int i = 0; i < columnModel.getColumnCount(); i++) {
            columnModel.getColumn(i).setPreferredWidth(0); // Resetea el ancho
            columnModel.getColumn(i).setPreferredWidth(getMaximumWidthForColumn(i));
        }
        
       CalcularTotal();
    }
    
     @Override
    public void dispose() {
         // Cerrar el JFrame sin cerrar la aplicaicon
        super.dispose();
    }

    /**
    *
    * devuleve el maximo ancho por columan
    * @param colum el numero de columna
    * @return un entero con el ancho 
    */
    private int getMaximumWidthForColumn(int column) {
        int maxWidth = 0;
        for (int row = 0; row < jTable1.getRowCount(); row++) {
            TableCellRenderer cellRenderer = jTable1.getCellRenderer(row, column);
            Object value = jTable1.getValueAt(row, column);
            Component cell = cellRenderer.getTableCellRendererComponent(jTable1, value, false, false, row, column);
            maxWidth = Math.max(maxWidth, cell.getPreferredSize().width);
        }
        return maxWidth + 10; // Agrega un pequeño espacio extra
    }
    
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        LblEfectivo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        LblTarjeta = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        LblTotal = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LblTrabajador = new javax.swing.JLabel();
        BtnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setIconImage(getIconImage());
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("DIARIO DE MOVIMIENTO INDIVIDUAL");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Totalizador:"));

        LblEfectivo.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        LblEfectivo.setText("0.0");

        jLabel6.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        jLabel6.setText("€    Efectivo");

        LblTarjeta.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        LblTarjeta.setText("0.0");

        jLabel8.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        jLabel8.setText("€    Tarjeta");

        jLabel9.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        jLabel9.setText("TOTAL:");

        LblTotal.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        LblTotal.setText("0.0");

        jLabel11.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        jLabel11.setText("€");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(LblEfectivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(97, 97, 97)
                .addComponent(LblTarjeta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(107, 107, 107)
                .addComponent(jLabel9)
                .addGap(27, 27, 27)
                .addComponent(LblTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LblTarjeta)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)
                        .addComponent(LblTotal)
                        .addComponent(jLabel11))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LblEfectivo)
                        .addComponent(jLabel6)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1069, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel2.setText("Trabajador:");

        LblTrabajador.setFont(new java.awt.Font("Open Sans", 3, 18)); // NOI18N
        LblTrabajador.setText("No identificado");

        BtnCerrar.setBackground(new java.awt.Color(255, 102, 102));
        BtnCerrar.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        BtnCerrar.setText("CERRAR");
        BtnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(401, 401, 401)
                        .addComponent(jLabel1)
                        .addGap(0, 422, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addComponent(LblTrabajador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(LblTrabajador))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_BtnCerrarActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCerrar;
    private javax.swing.JLabel LblEfectivo;
    private javax.swing.JLabel LblTarjeta;
    private javax.swing.JLabel LblTotal;
    private javax.swing.JLabel LblTrabajador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    /**
    *
    * calcula el total
    */
    private void CalcularTotal() {
    //si modificamos las columnas de las tablas, modificar estos numeros, la primera columna de la tabla es 0
    int columnaMedio=2;
    int columnaEntrada=5;
    //buscar en todas las columnas del jtable los importes de entrada y sumarlos
    double sum=0 ,sumEfect=0,sumTajeta = 0;
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            if (jTable1.getValueAt(i, columnaMedio).equals("Efectivo")){   //si cambiamos el orden de las columnas vigilar esta columna que debe ser medio de pago
               sumEfect += (double) jTable1.getValueAt(i, columnaEntrada);
            } else {
               sumTajeta += (double) jTable1.getValueAt(i, columnaEntrada);
            }
            sum += (double) jTable1.getValueAt(i, columnaEntrada); // Suma el valor de la columna "Entrada" en la fila i
        }
    this.LblEfectivo.setText(String.valueOf(sumEfect));
    this.LblTarjeta.setText(String.valueOf(sumTajeta));
    this.LblTotal.setText(String.valueOf(sum));
    
    }

    
}
