/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.aytomonzon.librosac;

import java.awt.Component;
import java.awt.print.PrinterException;
import java.text.MessageFormat;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableRowSorter;

/**
 * Clase generadora de informes de movimientos totales
 * @author albertoaraguas
 * @version 1.0
 */
public class InformeMovimientosTotales extends javax.swing.JFrame {

    /**
     * Creates new form InformeMovimientosTotales
     * @param miModelo3  es un defaulTableModel con los datos totales, solo los pinta en la table
     */
    public InformeMovimientosTotales(DefaultTableModel miModelo3) {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);   //con esto volvemos al jframe principal sin cerrar el programa
        //calrgamos el table con los datos de la consulta
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(miModelo3);
        this.jTable1.setModel(miModelo3);
        this.jTable1.setRowSorter(sorter);
        // Ajustar el ancho de las columnas
        TableColumnModel columnModel = jTable1.getColumnModel();
        for (int i = 0; i < columnModel.getColumnCount(); i++) {
            columnModel.getColumn(i).setPreferredWidth(0); // Resetea el ancho
            columnModel.getColumn(i).setPreferredWidth(getMaximumWidthForColumn(i));
        }
    }

    
    /**
     * hallar el maximo de ancho de columna
     * @param column  numero de columna
     * @return entero con el máximo
     */
    private int getMaximumWidthForColumn(int column) {
        int maxWidth = 0;
        for (int row = 0; row < jTable1.getRowCount(); row++) {
            TableCellRenderer cellRenderer = jTable1.getCellRenderer(row, column);
            Object value = jTable1.getValueAt(row, column);
            Component cell = cellRenderer.getTableCellRendererComponent(jTable1, value, false, false, row, column);
            maxWidth = Math.max(maxWidth, cell.getPreferredSize().width);
        }
        return maxWidth + 10; // Agrega un pequeño espacio extra
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblTituloTotales = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BtnCerrarTotales = new javax.swing.JButton();
        BtnImprimirTotales = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        LblTituloTotales.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        LblTituloTotales.setForeground(new java.awt.Color(0, 51, 204));
        LblTituloTotales.setText("Listado Movimientos Totales");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        BtnCerrarTotales.setBackground(new java.awt.Color(255, 153, 204));
        BtnCerrarTotales.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        BtnCerrarTotales.setText("CERRAR");
        BtnCerrarTotales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCerrarTotalesActionPerformed(evt);
            }
        });

        BtnImprimirTotales.setBackground(new java.awt.Color(204, 153, 255));
        BtnImprimirTotales.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        BtnImprimirTotales.setText("IMPRIMIR");
        BtnImprimirTotales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnImprimirTotalesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnImprimirTotales, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnCerrarTotales, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(LblTituloTotales)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblTituloTotales)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnImprimirTotales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnCerrarTotales, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * cerrar frame
     */
    private void BtnCerrarTotalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCerrarTotalesActionPerformed
           dispose();
    }//GEN-LAST:event_BtnCerrarTotalesActionPerformed
    /**
     * hallar el maximo de ancho de columna
     */
    private void BtnImprimirTotalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnImprimirTotalesActionPerformed
        //imprime en la impresora el jtable
        try {
            MessageFormat header = new MessageFormat("MOVIMIENTOS TOTALES");
            MessageFormat footer = new MessageFormat("Página {0,number,integer}");
            this.jTable1.print(JTable.PrintMode.FIT_WIDTH, header, footer); //envia los datos de la tabla a la impresora
        } catch (PrinterException ex) {
            System.err.println("Fallo al imprimir");
        }
    }//GEN-LAST:event_BtnImprimirTotalesActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCerrarTotales;
    private javax.swing.JButton BtnImprimirTotales;
    private javax.swing.JLabel LblTituloTotales;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
