/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.aytomonzon.librosac;

import com.toedter.calendar.JDateChooser;
import java.awt.Desktop;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.net.MalformedURLException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 * Clase que saca los movimientos detallados
 * @author albertoaraguas
 * @version 1.0
 */
public class MovimientoDetallado extends javax.swing.JFrame {

    JDateChooser dateChooser1 = new JDateChooser();
    ConectorDB basedatos;    
    Herramientas herramientas = new Herramientas();
    String FechaInicial="";
    String FechaFinal="";
    String intervaloFechas="";
    String Libro="1";  //1 para efetivo y 2 para tarjeta
    
    /**
     * Creates new form MovimientoDetallado
     * @param basedatos
     * @throws java.sql.SQLException
     */
    public MovimientoDetallado(ConectorDB basedatos) throws SQLException {
        this.basedatos=basedatos;
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);   //con esto volvemos al jframe principal sin cerrar el programa
        PonerFecha();
        cargarListaUsuarios();
        cargarListaConceptos();
        //habilitamos panel usuarios y deshabilitamos panel concepto
        this.ListaConceptos.setVisible(false);
    }

    private void cargarListaUsuarios() throws SQLException{
        //if(basedatos.isConected()){
            this.ListaUsuarios.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
            String[] usuarios = basedatos.getTrabajadores();
            // Step 2: Create a DefaultListModel object
            DefaultListModel<String> listModel = new DefaultListModel<>();
            // Step 3: Use the addElement() method to add each String to the DefaultListModel object
            for (String item : usuarios) {
                listModel.addElement(item);
            }
            // Step 4: Set the DefaultListModel object as the model for the JList component
            this.ListaUsuarios.setModel(listModel);
            //seleccionar todos los usuarios
            this.ListaUsuarios.setSelectionInterval(0, ListaUsuarios.getModel().getSize() - 1);
        //}
     }
    
    
    
    private void cargarListaConceptos() throws SQLException{
        //if(basedatos.isConected()){
            this.ListaConceptos.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
            String[] conceptos = basedatos.getConceptos();
            // Step 2: Create a DefaultListModel object
            DefaultListModel<String> listModel = new DefaultListModel<>();
            // Step 3: Use the addElement() method to add each String to the DefaultListModel object
            for (String item : conceptos) {
                listModel.addElement(item);
            }
            // Step 4: Set the DefaultListModel object as the model for the JList component
            this.ListaConceptos.setModel(listModel);
            //seleccionar todos los usuarios
            this.ListaConceptos.setSelectionInterval(0, ListaConceptos.getModel().getSize() - 1);
        //}
    }
    
    
    
    private void PonerFecha(){
    // Formatear la fecha en el formato deseado (día/mes/año)
        Date fechaActual = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String fechaFormateada = sdf.format(fechaActual);
        this.jTextField9.setText(fechaFormateada);
        this.jTextField10.setText(fechaFormateada);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnCerrar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        BtnSeleccionarFecha = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        BtnFechaFinal = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaUsuarios = new javax.swing.JList<>();
        BtnSeleccionarTodoUsuarios = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaConceptos = new javax.swing.JList<>();
        BtnSeleccionarTodoConceptos = new javax.swing.JButton();
        BtnTotales = new javax.swing.JButton();
        BtnConsultaDetallada = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        BtnCerrar.setBackground(new java.awt.Color(255, 102, 102));
        BtnCerrar.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        BtnCerrar.setText("CERRAR");
        BtnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCerrarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Selecciona"));

        jCheckBox1.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jCheckBox1.setText("Por concepto");
        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox1ItemStateChanged(evt);
            }
        });

        jCheckBox2.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jCheckBox2.setSelected(true);
        jCheckBox2.setText("Por usuario");
        jCheckBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox2ItemStateChanged(evt);
            }
        });
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox3.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jCheckBox3.setSelected(true);
        jCheckBox3.setText("Efectivo");
        jCheckBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox3ItemStateChanged(evt);
            }
        });
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jCheckBox4.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jCheckBox4.setText("Tarjeta");
        jCheckBox4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox4ItemStateChanged(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jLabel9.setText("Fecha inicial:");
        jLabel9.setToolTipText("");

        jTextField9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField9.setText("hoy");
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        BtnSeleccionarFecha.setLabel("F");
        BtnSeleccionarFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSeleccionarFechaActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jLabel10.setText("Fecha final:");
        jLabel10.setToolTipText("");

        jTextField10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField10.setText("hoy");
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });

        BtnFechaFinal.setLabel("F");
        BtnFechaFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFechaFinalActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuarios"));

        ListaUsuarios.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        ListaUsuarios.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(ListaUsuarios);

        BtnSeleccionarTodoUsuarios.setBackground(java.awt.Color.pink);
        BtnSeleccionarTodoUsuarios.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        BtnSeleccionarTodoUsuarios.setText("Seleccionar todo");
        BtnSeleccionarTodoUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSeleccionarTodoUsuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnSeleccionarTodoUsuarios))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnSeleccionarTodoUsuarios))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Conceptos"));

        ListaConceptos.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        ListaConceptos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(ListaConceptos);

        BtnSeleccionarTodoConceptos.setBackground(java.awt.Color.pink);
        BtnSeleccionarTodoConceptos.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        BtnSeleccionarTodoConceptos.setText("Seleccionar todo");
        BtnSeleccionarTodoConceptos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSeleccionarTodoConceptosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(BtnSeleccionarTodoConceptos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnSeleccionarTodoConceptos))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnSeleccionarFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox4))
                .addGap(38, 38, 38)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnSeleccionarFecha))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnFechaFinal))
                .addContainerGap(34, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        BtnTotales.setBackground(new java.awt.Color(0, 204, 204));
        BtnTotales.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        BtnTotales.setText("CONSULTA TOTALES");
        BtnTotales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTotalesActionPerformed(evt);
            }
        });

        BtnConsultaDetallada.setBackground(new java.awt.Color(0, 204, 204));
        BtnConsultaDetallada.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        BtnConsultaDetallada.setText("CONSULTA DETALLADA");
        BtnConsultaDetallada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConsultaDetalladaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 106, Short.MAX_VALUE)
                        .addComponent(BtnTotales, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(BtnConsultaDetallada, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(BtnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BtnConsultaDetallada, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                        .addComponent(BtnCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                    .addComponent(BtnTotales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_BtnCerrarActionPerformed

    private void BtnFechaFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFechaFinalActionPerformed
        int result = JOptionPane.showConfirmDialog(null, dateChooser1, "Seleccionar Fecha", JOptionPane.OK_CANCEL_OPTION);
        if (result == JOptionPane.OK_OPTION) {
            // Obtener la fecha seleccionada
            Date selectedDate = dateChooser1.getDate();
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            String formattedDate = sdf.format(selectedDate);
            this.jTextField10.setText(formattedDate);
        }
    }//GEN-LAST:event_BtnFechaFinalActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void BtnSeleccionarFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSeleccionarFechaActionPerformed

        int result = JOptionPane.showConfirmDialog(null, dateChooser1, "Seleccionar Fecha", JOptionPane.OK_CANCEL_OPTION);
        if (result == JOptionPane.OK_OPTION) {
            // Obtener la fecha seleccionada
            Date selectedDate = dateChooser1.getDate();
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            String formattedDate = sdf.format(selectedDate);
            this.jTextField9.setText(formattedDate);
            // JOptionPane.showMessageDialog(null, "Fecha seleccionada: " + selectedDate.toString());
        }
        //this.jTextField9.setText(fechaseleccion.toString());
    }//GEN-LAST:event_BtnSeleccionarFechaActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jCheckBox4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox4ItemStateChanged
        if (this.jCheckBox4.isSelected()){
            //por usuario esta seleccionado
            this.jCheckBox3.setSelected(false);

        }
    }//GEN-LAST:event_jCheckBox4ItemStateChanged

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox3ItemStateChanged
        if (this.jCheckBox3.isSelected()){
            //por usuario esta seleccionado
            this.jCheckBox4.setSelected(false);

        }
    }//GEN-LAST:event_jCheckBox3ItemStateChanged

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed

    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox2ItemStateChanged
        if (this.jCheckBox2.isSelected()){
            //por usuario esta seleccionado
            this.jCheckBox1.setSelected(false);
            //habilitamos panel usuarios y deshabilitamos panel concepto
            this.ListaUsuarios.setVisible(true);
            this.ListaConceptos.setVisible(false);
        }
    }//GEN-LAST:event_jCheckBox2ItemStateChanged

    private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox1ItemStateChanged
        if (this.jCheckBox1.isSelected()){
            //por concepto esta seleccionado
            this.jCheckBox2.setSelected(false);
            //habilitamos panel conceptos y deshabilitamos panel usuarios
            this.ListaUsuarios.setVisible(false);
            this.ListaConceptos.setVisible(true);
        }
    }//GEN-LAST:event_jCheckBox1ItemStateChanged

    private void BtnSeleccionarTodoUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSeleccionarTodoUsuariosActionPerformed
         this.ListaUsuarios.setSelectionInterval(0, ListaUsuarios.getModel().getSize() - 1);
    }//GEN-LAST:event_BtnSeleccionarTodoUsuariosActionPerformed

    private void BtnSeleccionarTodoConceptosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSeleccionarTodoConceptosActionPerformed
        this.ListaConceptos.setSelectionInterval(0, ListaConceptos.getModel().getSize() - 1);
    }//GEN-LAST:event_BtnSeleccionarTodoConceptosActionPerformed

    private void CargarParametrosConsulta(){
        FechaInicial= herramientas.cambiarOrdenFecha(this.jTextField9.getText(),true);
        FechaFinal= herramientas.cambiarOrdenFecha(this.jTextField10.getText(),true);
        intervaloFechas = "Fecha BETWEEN '"+FechaInicial+"' AND '"+FechaFinal+"'";
            //comprobamos el libro a consultar
        if (this.jCheckBox3.isSelected()){
            Libro="1";
        }else if (this.jCheckBox4.isSelected()){
            Libro="2";
        }
    }
    //devuelve un strig con los conceptos seleccionados, separados por comas
    private String CargarConceptosSeleccionados(){
      String Listado="";
      List<String> SelectedValues= this.ListaConceptos.getSelectedValuesList();
                for (Object SelectedValue : SelectedValues){
                    Listado += " '"+SelectedValue.toString()+"',";
                }
                Listado=Listado.substring(0, Listado.length()-1);
      return Listado;          
    }
    //devuelve un strig con los usuarios seleccionados, separados por comas
    private String CargarUsuariosSeleccionados(){
    String Listado="";
      List<String> SelectedValues= this.ListaUsuarios.getSelectedValuesList();
                for (Object SelectedValue : SelectedValues){
                    Listado += " '"+SelectedValue.toString()+"',";
                }
                Listado=Listado.substring(0, Listado.length()-1);
      return Listado;     
    
    }
       
    
    private void BtnTotalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTotalesActionPerformed
        // hace la consulta y lo mete en la pantalla informemovimientostotales
        CargarParametrosConsulta();
        String ListadoConceptos;
        String ConsultaTotales="";
        if (this.jCheckBox1.isSelected()){
            //si esta seleccionado por concepto
            //hacemos una lista de los conceptos seleccionados
            ListadoConceptos=CargarConceptosSeleccionados();
            ConsultaTotales= "SELECT c.CDescripcion as Concepto, SUM(Entrada) as Total_Entradas,SUM(Salida) as Total_Salidas " +
                    "FROM Apuntes ap " +
                    "JOIN Concepto c ON ap.Concepto = c.IdConcepto "+
                    "WHERE Libro="+Libro+" "+
                    "AND "+intervaloFechas+
                    " AND c.CDescripcion IN ("+ListadoConceptos+")"+
                    " GROUP BY ap.Concepto";
        } else if (this.jCheckBox2.isSelected()){
            //si esta seleccionado por usuario
            ListadoConceptos=CargarUsuariosSeleccionados();
            ConsultaTotales= "SELECT usuario as Usuario, SUM(Entrada) as Total_Entradas,SUM(Salida) as Total_Salidas " +
                    "FROM Apuntes " +
                    "WHERE Libro="+Libro+" "+
                    "AND "+intervaloFechas+
                    " AND usuario IN ("+ListadoConceptos+")"+
                    " GROUP BY usuario";
        }
        //if(basedatos.isConected()){
        DefaultTableModel miModelo3 = basedatos.consulta(ConsultaTotales);
        InformeMovimientosTotales totalesI = new InformeMovimientosTotales(miModelo3);
        totalesI.setLocationRelativeTo(null);
        totalesI.setTitle("Diario Movimientos Individual");
        totalesI.setIconImage(prepareImage("C:/librocaja/images/ico.jpg", 32, 32));
        totalesI.setVisible(true);
        //}
    }//GEN-LAST:event_BtnTotalesActionPerformed

    private void BtnConsultaDetalladaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConsultaDetalladaActionPerformed
        CargarParametrosConsulta();  // ponemos los datos correctos en libro e intervalofechas
        try {
            // llamamos a las clases , de momento esta en desarrollo
            if (this.jCheckBox1.isSelected()){
                try {
                    //seleccionado conceptos
                    InformeMovimientoConcepto inf1= new InformeMovimientoConcepto(basedatos,CargarConceptosSeleccionados(),Libro,intervaloFechas); //crear clase informe conceptos
                } catch (SQLException ex) {
                   JOptionPane.showMessageDialog(null, "Error acceso a la base de datos", "Warning", JOptionPane.WARNING_MESSAGE);
                }
                //inf1.GenerarInforme();
                File file = new File("C:\\librocaja\\Recibo\\InformeConcepto.pdf");
                Desktop.getDesktop().open(file);
            } else if (this.jCheckBox2.isSelected()){
                //seleccionado usuarios
                InformeMovimientoUsuario inf1= new InformeMovimientoUsuario(basedatos,CargarUsuariosSeleccionados(),Libro,intervaloFechas);
                //inf1.GenerarInforme();
                File file = new File("C:\\librocaja\\Recibo\\InformeUsuario.pdf");
                Desktop.getDesktop().open(file);
            }
            
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Archivo no encontrado.", "Warning", JOptionPane.WARNING_MESSAGE);
        } catch (MalformedURLException ex) {
            JOptionPane.showMessageDialog(null, "Ruta erronea", "Warning", JOptionPane.WARNING_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error de acceso al archivo", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_BtnConsultaDetalladaActionPerformed

 public Image prepareImage(String imagePath, int targetWidth, int targetHeight) {
        Image originalImage = Toolkit.getDefaultToolkit().getImage(imagePath);
        Image resultingImage = originalImage.getScaledInstance(targetWidth, targetHeight, Image.SCALE_SMOOTH);
        return resultingImage;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCerrar;
    private javax.swing.JButton BtnConsultaDetallada;
    private javax.swing.JButton BtnFechaFinal;
    private javax.swing.JButton BtnSeleccionarFecha;
    private javax.swing.JButton BtnSeleccionarTodoConceptos;
    private javax.swing.JButton BtnSeleccionarTodoUsuarios;
    private javax.swing.JButton BtnTotales;
    private javax.swing.JList<String> ListaConceptos;
    private javax.swing.JList<String> ListaUsuarios;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
